### ISSUE TITLE
import failure- likely due to scipy 1.13 and 1.12

### ISSUE THREAD

**Issue by connor-french** [pysal/esda#290]
I am attempting to import `esda` v2.4.1 in an isolated environment and get the following error:

```
Python 3.11.8 | packaged by conda-forge | (main, Feb 16 2024, 20:49:36) [Clang 16.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import esda
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/connorfrench/miniforge3/envs/spaceprime/lib/python3.11/site-packages/esda/__init__.py", line 7, in <module>
    from . import adbscan
  File "/Users/connorfrench/miniforge3/envs/spaceprime/lib/python3.11/site-packages/esda/adbscan.py", line 10, in <module>
    from libpysal.cg.alpha_shapes import alpha_shape_auto
  File "/Users/connorfrench/miniforge3/envs/spaceprime/lib/python3.11/site-packages/libpysal/__init__.py", line 27, in <module>
    from . import cg
  File "/Users/connorfrench/miniforge3/envs/spaceprime/lib/python3.11/site-packages/libpysal/cg/__init__.py", line 7, in <module>
    from .kdtree import *
  File "/Users/connorfrench/miniforge3/envs/spaceprime/lib/python3.11/site-packages/libpysal/cg/kdtree.py", line 9, in <module>
    from scipy import inf
ImportError: cannot import name 'inf' from 'scipy' (/Users/connorfrench/miniforge3/envs/spaceprime/lib/python3.11/site-packages/scipy/__init__.py)
```

Originally I was using `scipy` v1.13.0 and downgraded to v1.12.0 to see if that worked, but had the same error. When I downgraded to `scipy` 1.11.4, the import worked successfully. Maybe it's a change in `scipy `naming?

**Comment by martinfleis** [comment]
It's been already fixed. Ensure you use the latest libpysal 4.10.
